### PR TITLE
New features on TO DO list

### PR DESCRIPTION
**Pull request by plally**
- Made python 3 compatible
- Added sounds
- Also, added a "conventional" Asteroids shield mode option (defaults to author's original).

### CODE REVIEW

**Comment by jcupitt** [comment]
Hey, that's great! I'll read through your pull request tonight.

**Comment by jcupitt** [comment]
Hi, I merged your branch with no changes here:

https://github.com/jcupitt/argh-steroids/commit/3397a958f0b4e72c7b58e7508f52f620fd21eb16

There are a few small formatting changes I'd like to make to keep the code consistent, like using snake_case for member names, I'll put those in a separate commit.

Thanks again for this new stuff!

**Comment by jcupitt** [comment]
I've made a few more changes and put in some background music. I've added your name to the "authors" thing on the README, I hope that's OK. 

I notices you copied the particle array before updating it. I'm not sure that's necessary, since it loops over the keys rather than the array itself, so I changed that back.

**Comment by plally** [comment]
Yeah thanks that's great. You can do whatever you want with it. It is your game after all.

**Pull request merged**
